/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelfCheckRouteImport } from './routes/self-check'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as CareerRouteImport } from './routes/career'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfCheckRoute = SelfCheckRouteImport.update({
  id: '/self-check',
  path: '/self-check',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/evidence': typeof EvidenceRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRoute
  '/self-check': typeof SelfCheckRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/evidence': typeof EvidenceRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRoute
  '/self-check': typeof SelfCheckRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/evidence': typeof EvidenceRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRoute
  '/self-check': typeof SelfCheckRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/evidence'
    | '/login'
    | '/mentor'
    | '/profile'
    | '/recruiter'
    | '/self-check'
    | '/signup'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/evidence'
    | '/login'
    | '/mentor'
    | '/profile'
    | '/recruiter'
    | '/self-check'
    | '/signup'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/evidence'
    | '/login'
    | '/mentor'
    | '/profile'
    | '/recruiter'
    | '/self-check'
    | '/signup'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRoute
  EvidenceRoute: typeof EvidenceRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  ProfileRoute: typeof ProfileRoute
  RecruiterRoute: typeof RecruiterRoute
  SelfCheckRoute: typeof SelfCheckRoute
  SignupRoute: typeof SignupRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-check': {
      id: '/self-check'
      path: '/self-check'
      fullPath: '/self-check'
      preLoaderRoute: typeof SelfCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRoute,
  EvidenceRoute: EvidenceRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  ProfileRoute: ProfileRoute,
  RecruiterRoute: RecruiterRoute,
  SelfCheckRoute: SelfCheckRoute,
  SignupRoute: SignupRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
